In [1]:
import tensorflow as tf
print(tf.__version__)


2.15.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## define the vocabulary size
voc_size = 10000

In [6]:
## One Hot Representation
one_hot_rep = [one_hot(words,voc_size) for words in sent]
one_hot_rep

[[4150, 130, 4269, 5476],
 [4150, 130, 4269, 1631],
 [4150, 4560, 4269, 7757],
 [7873, 7129, 345, 3667, 6439],
 [7873, 7129, 345, 3667, 3113],
 [3482, 4150, 9827, 4269, 5547],
 [8401, 9163, 4819, 3667]]

In [7]:
## word embedding repr

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 4150  130 4269 5476]
 [   0    0    0    0 4150  130 4269 1631]
 [   0    0    0    0 4150 4560 4269 7757]
 [   0    0    0 7873 7129  345 3667 6439]
 [   0    0    0 7873 7129  345 3667 3113]
 [   0    0    0 3482 4150 9827 4269 5547]
 [   0    0    0    0 8401 9163 4819 3667]]


In [10]:
# feature repr
dim = 10


In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 227ms/step


array([[[ 0.00757559, -0.01635387, -0.01945706, -0.03728276,
          0.02676462, -0.03235885,  0.0107939 ,  0.03605935,
         -0.02828686, -0.0425705 ],
        [ 0.00757559, -0.01635387, -0.01945706, -0.03728276,
          0.02676462, -0.03235885,  0.0107939 ,  0.03605935,
         -0.02828686, -0.0425705 ],
        [ 0.00757559, -0.01635387, -0.01945706, -0.03728276,
          0.02676462, -0.03235885,  0.0107939 ,  0.03605935,
         -0.02828686, -0.0425705 ],
        [ 0.00757559, -0.01635387, -0.01945706, -0.03728276,
          0.02676462, -0.03235885,  0.0107939 ,  0.03605935,
         -0.02828686, -0.0425705 ],
        [-0.00427079,  0.04032651,  0.00986167, -0.02722185,
          0.00833225, -0.02568694,  0.03811712, -0.03720104,
         -0.00313789, -0.00202359],
        [ 0.04281965, -0.04511715,  0.01385954, -0.02624228,
          0.0461737 ,  0.00238397, -0.03329463, -0.02205314,
          0.02301199,  0.0175839 ],
        [-0.03732558, -0.01430794, -0.03728683, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4150,  130, 4269, 5476])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 85ms/step


array([[ 0.00757559, -0.01635387, -0.01945706, -0.03728276,  0.02676462,
        -0.03235885,  0.0107939 ,  0.03605935, -0.02828686, -0.0425705 ],
       [ 0.00757559, -0.01635387, -0.01945706, -0.03728276,  0.02676462,
        -0.03235885,  0.0107939 ,  0.03605935, -0.02828686, -0.0425705 ],
       [ 0.00757559, -0.01635387, -0.01945706, -0.03728276,  0.02676462,
        -0.03235885,  0.0107939 ,  0.03605935, -0.02828686, -0.0425705 ],
       [ 0.00757559, -0.01635387, -0.01945706, -0.03728276,  0.02676462,
        -0.03235885,  0.0107939 ,  0.03605935, -0.02828686, -0.0425705 ],
       [-0.00427079,  0.04032651,  0.00986167, -0.02722185,  0.00833225,
        -0.02568694,  0.03811712, -0.03720104, -0.00313789, -0.00202359],
       [ 0.04281965, -0.04511715,  0.01385954, -0.02624228,  0.0461737 ,
         0.00238397, -0.03329463, -0.02205314,  0.02301199,  0.0175839 ],
       [-0.03732558, -0.01430794, -0.03728683, -0.01965382, -0.00805024,
        -0.00644119, -0.00520266, -0.03109158